[package]
name = "worktree-manager"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
git2 = { version = "0.20.2", features = ["ssh", "https", "vendored-libgit2"] }
