add_newline = false
format = """
[\\[](fg:#A9A9A9)\
$username\
[\\]](fg:#A9A9A9) \
$directory \
$git_branch\
\n$character\
"""

[username]
style_root = "red"
style_user = "fg:#A9A9A9"
format = "[$user]($style)"
show_always = true

[hostname]
ssh_only = false
ssh_symbol = ""
style = "fg:#A9A9A9"
format = "[$hostname]($style)"

[directory]
truncation_length = 8
truncation_symbol = "#"
truncate_to_repo = true
style = "blue"
format = "[$path]($style)"

[git_branch]
symbol = ""
truncation_symbol = ""
style = "fg:#702963"
format = "[\\($branch\\)]($style)"

[character]
success_symbol = "[\\$](green)"
error_symbol = "[\\$](red)"
vimcmd_symbol = "[\\$](green)"
